
import 'package:cryptocalc/currency/model/country.dart';

final List<Country> countryList = [
  Country(
      name: "Andorra",
      isoCode: "AD",
      iso3Code: "AND",
      phoneCode: "376",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "United Arab Emirates",
      isoCode: "AE",
      iso3Code: "ARE",
      phoneCode: "971",
      currencyCode: "AED",
      currencyName: "United Arab Emirates dirham",
      isPicked: false,),
  Country(
      name: "Afghanistan",
      isoCode: "AF",
      iso3Code: "AFG",
      phoneCode: "93",
      currencyCode: "AFN",
      currencyName: "Afghan afghani", 
      isPicked: false),
  Country(
      name: "Antigua and Barbuda",
      isoCode: "AG",
      iso3Code: "ATG",
      phoneCode: "1-268",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Anguilla",
      isoCode: "AI",
      iso3Code: "AIA",
      phoneCode: "1-264",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Albania",
      isoCode: "AL",
      iso3Code: "ALB",
      phoneCode: "355",
      currencyCode: "ALL",
      currencyName: "Albanian lek", 
      isPicked: false),
  Country(
      name: "Armenia",
      isoCode: "AM",
      iso3Code: "ARM",
      phoneCode: "374",
      currencyCode: "AMD",
      currencyName: "Armenian dram", 
      isPicked: false),
  Country(
      name: "Angola",
      isoCode: "AO",
      iso3Code: "AGO",
      phoneCode: "244",
      currencyCode: "AOA",
      currencyName: "Angolan kwanza", 
      isPicked: false),
  Country(
      name: "Antarctica",
      isoCode: "AQ",
      iso3Code: "ATA",
      phoneCode: "672",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Argentina",
      isoCode: "AR",
      iso3Code: "ARG",
      phoneCode: "54",
      currencyCode: "ARS",
      currencyName: "Argentine peso", 
      isPicked: false),
  Country(
      name: "American Samoa",
      isoCode: "AS",
      iso3Code: "ASM",
      phoneCode: "1-684",
      currencyCode: "USD",
      currencyName: "United State Dollar", 
      isPicked: false),
  Country(
      name: "Austria",
      isoCode: "AT",
      iso3Code: "AUT",
      phoneCode: "43",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Australia",
      isoCode: "AU",
      iso3Code: "AUS",
      phoneCode: "61",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Aruba",
      isoCode: "AW",
      iso3Code: "ABW",
      phoneCode: "297",
      currencyCode: "AWG",
      currencyName: "Aruban florin", 
      isPicked: false),
  Country(
      name: "Åland Islands",
      isoCode: "AX",
      iso3Code: "ALA",
      phoneCode: "358",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Azerbaijan",
      isoCode: "AZ",
      iso3Code: "AZE",
      phoneCode: "994",
      currencyCode: "AZN",
      currencyName: "Azerbaijani manat", 
      isPicked: false),
  Country(
      name: "Bosnia and Herzegovina",
      isoCode: "BA",
      iso3Code: "BIH",
      phoneCode: "387",
      currencyCode: "BAM",
      currencyName: "Bosnia and Herzegovina convertible mark", 
      isPicked: false),
  Country(
      name: "Barbados",
      isoCode: "BB",
      iso3Code: "BRB",
      phoneCode: "1-246",
      currencyCode: "BBD",
      currencyName: "Barbadian dollar", 
      isPicked: false),
  Country(
      name: "Bangladesh",
      isoCode: "BD",
      iso3Code: "BGD",
      phoneCode: "880",
      currencyCode: "BDT",
      currencyName: "Bangladeshi taka", 
      isPicked: false),
  Country(
      name: "Belgium",
      isoCode: "BE",
      iso3Code: "BEL",
      phoneCode: "32",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Burkina Faso",
      isoCode: "BF",
      iso3Code: "BFA",
      phoneCode: "226",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Bulgaria",
      isoCode: "BG",
      iso3Code: "BGR",
      phoneCode: "359",
      currencyCode: "BGN",
      currencyName: "Bulgarian lev", 
      isPicked: false),
  Country(
      name: "Bahrain",
      isoCode: "BH",
      iso3Code: "BHR",
      phoneCode: "973",
      currencyCode: "BHD",
      currencyName: "Bahraini dinar", 
      isPicked: false),
  Country(
      name: "Burundi",
      isoCode: "BI",
      iso3Code: "BDI",
      phoneCode: "257",
      currencyCode: "BIF",
      currencyName: "Burundian franc", 
      isPicked: false),
  Country(
      name: "Benin",
      isoCode: "BJ",
      iso3Code: "BEN",
      phoneCode: "229",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Saint Barthélemy",
      isoCode: "BL",
      iso3Code: "BLM",
      phoneCode: "590",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Bermuda",
      isoCode: "BM",
      iso3Code: "BMU",
      phoneCode: "1-441",
      currencyCode: "BMD",
      currencyName: "Bermudian dollar", 
      isPicked: false),
  Country(
      name: "Brunei Darussalam",
      isoCode: "BN",
      iso3Code: "BRN",
      phoneCode: "673",
      currencyCode: "BND",
      currencyName: "Brunei dollar", 
      isPicked: false),
  Country(
      name: "Bolivia, Plurinational State of",
      isoCode: "BO",
      iso3Code: "BOL",
      phoneCode: "591",
      currencyCode: "BOB",
      currencyName: "Bolivian boliviano", 
      isPicked: false),
  Country(
      name: "Caribbean Netherlands",
      isoCode: "BQ",
      iso3Code: "BES",
      phoneCode: "599",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Brazil",
      isoCode: "BR",
      iso3Code: "BRA",
      phoneCode: "55",
      currencyCode: "BRL",
      currencyName: "Brazilian real", 
      isPicked: false),
  Country(
      name: "Bahamas",
      isoCode: "BS",
      iso3Code: "BHS",
      phoneCode: "1-242",
      currencyCode: "BSD",
      currencyName: "Bahamian dollar", 
      isPicked: false),
  Country(
      name: "Bhutan",
      isoCode: "BT",
      iso3Code: "BTN",
      phoneCode: "975",
      currencyCode: "BTN",
      currencyName: "Bhutanese ngultrum", 
      isPicked: false),
  Country(
      name: "Bouvet Island",
      isoCode: "BV",
      iso3Code: "BVT",
      phoneCode: "47",
      currencyCode: "NOK",
      currencyName: "Norwegian krone", 
      isPicked: false),
  Country(
      name: "Botswana",
      isoCode: "BW",
      iso3Code: "BWA",
      phoneCode: "267",
      currencyCode: "BWP",
      currencyName: "Botswana pula", 
      isPicked: false),
  Country(
      name: "Belarus",
      isoCode: "BY",
      iso3Code: "BLR",
      phoneCode: "375",
      currencyCode: "BYN",
      currencyName: "New Belarusian ruble", 
      isPicked: false),
  Country(
      name: "Belize",
      isoCode: "BZ",
      iso3Code: "BLZ",
      phoneCode: "501",
      currencyCode: "BZD",
      currencyName: "Belize dollar", 
      isPicked: false),
  Country(
      name: "Canada",
      isoCode: "CA",
      iso3Code: "CAN",
      phoneCode: "1",
      currencyCode: "CAD",
      currencyName: "Canadian dollar", 
      isPicked: false),
  Country(
      name: "Cocos (Keeling) Islands",
      isoCode: "CC",
      iso3Code: "CCK",
      phoneCode: "61",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Congo, the Democratic Republic of the",
      isoCode: "CD",
      iso3Code: "COD",
      phoneCode: "243",
      currencyCode: "CDF",
      currencyName: "Congolese franc", 
      isPicked: false),
  Country(
      name: "Central African Republic",
      isoCode: "CF",
      iso3Code: "CAF",
      phoneCode: "236",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "Congo",
      isoCode: "CG",
      iso3Code: "COG",
      phoneCode: "242",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "Switzerland",
      isoCode: "CH",
      iso3Code: "CHE",
      phoneCode: "41",
      currencyCode: "CHF",
      currencyName: "Swiss franc", 
      isPicked: false),
  Country(
      name: "Côte d'Ivoire",
      isoCode: "CI",
      iso3Code: "CIV",
      phoneCode: "225",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Cook Islands",
      isoCode: "CK",
      iso3Code: "COK",
      phoneCode: "682",
      currencyCode: "NZD",
      currencyName: "New Zealand dollar", 
      isPicked: false),
  Country(
      name: "Chile",
      isoCode: "CL",
      iso3Code: "CHL",
      phoneCode: "56",
      currencyCode: "CLP",
      currencyName: "Chilean peso", 
      isPicked: false),
  Country(
      name: "Cameroon",
      isoCode: "CM",
      iso3Code: "CMR",
      phoneCode: "237",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "China",
      isoCode: "CN",
      iso3Code: "CHN",
      phoneCode: "86",
      currencyCode: "CNY",
      currencyName: "Chinese yuan", 
      isPicked: false),
  Country(
      name: "Colombia",
      isoCode: "CO",
      iso3Code: "COL",
      phoneCode: "57",
      currencyCode: "COP",
      currencyName: "Colombian peso", 
      isPicked: false),
  Country(
      name: "Costa Rica",
      isoCode: "CR",
      iso3Code: "CRI",
      phoneCode: "506",
      currencyCode: "CRC",
      currencyName: "Costa Rican colón", 
      isPicked: false),
  Country(
      name: "Cuba",
      isoCode: "CU",
      iso3Code: "CUB",
      phoneCode: "53",
      currencyCode: "CUC",
      currencyName: "Cuban convertible peso", 
      isPicked: false),
  Country(
      name: "Cape Verde",
      isoCode: "CV",
      iso3Code: "CPV",
      phoneCode: "238",
      currencyCode: "CVE",
      currencyName: "Cape Verdean escudo", 
      isPicked: false),
  Country(
      name: "Curaçao",
      isoCode: "CW",
      iso3Code: "CUW",
      phoneCode: "599",
      currencyCode: "ANG",
      currencyName: "Netherlands Antillean guilder", 
      isPicked: false),
  Country(
      name: "Christmas Island",
      isoCode: "CX",
      iso3Code: "CXR",
      phoneCode: "61",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Cyprus",
      isoCode: "CY",
      iso3Code: "CYP",
      phoneCode: "357",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Czech Republic",
      isoCode: "CZ",
      iso3Code: "CZE",
      phoneCode: "420",
      currencyCode: "CZK",
      currencyName: "Czech koruna", 
      isPicked: false),
  Country(
      name: "Germany",
      isoCode: "DE",
      iso3Code: "DEU",
      phoneCode: "49",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Djibouti",
      isoCode: "DJ",
      iso3Code: "DJI",
      phoneCode: "253",
      currencyCode: "DJF",
      currencyName: "Djiboutian franc", 
      isPicked: false),
  Country(
      name: "Denmark",
      isoCode: "DK",
      iso3Code: "DNK",
      phoneCode: "45",
      currencyCode: "DKK",
      currencyName: "Danish krone", 
      isPicked: false),
  Country(
      name: "Dominica",
      isoCode: "DM",
      iso3Code: "DMA",
      phoneCode: "1-767",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Dominican Republic",
      isoCode: "DO",
      iso3Code: "DOM",
      phoneCode: "1-849",
      currencyCode: "DOP",
      currencyName: "Dominican peso", 
      isPicked: false),
  Country(
      name: "Algeria",
      isoCode: "DZ",
      iso3Code: "DZA",
      phoneCode: "213",
      currencyCode: "DZD",
      currencyName: "Algerian dinar", 
      isPicked: false),
  Country(
      name: "Ecuador",
      isoCode: "EC",
      iso3Code: "ECU",
      phoneCode: "593",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Estonia",
      isoCode: "EE",
      iso3Code: "EST",
      phoneCode: "372",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Egypt",
      isoCode: "EG",
      iso3Code: "EGY",
      phoneCode: "20",
      currencyCode: "EGP",
      currencyName: "Egyptian pound", 
      isPicked: false),
  Country(
      name: "Western Sahara",
      isoCode: "EH",
      iso3Code: "ESH",
      phoneCode: "212",
      currencyCode: "MAD",
      currencyName: "Moroccan dirham", 
      isPicked: false),
  Country(
      name: "Eritrea",
      isoCode: "ER",
      iso3Code: "ERI",
      phoneCode: "291",
      currencyCode: "ERN",
      currencyName: "Eritrean nakfa", 
      isPicked: false),
  Country(
      name: "Spain",
      isoCode: "ES",
      iso3Code: "ESP",
      phoneCode: "34",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Ethiopia",
      isoCode: "ET",
      iso3Code: "ETH",
      phoneCode: "251",
      currencyCode: "ETB",
      currencyName: "Ethiopian birr", 
      isPicked: false),
  Country(
      name: "Finland",
      isoCode: "FI",
      iso3Code: "FIN",
      phoneCode: "358",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Fiji",
      isoCode: "FJ",
      iso3Code: "FJI",
      phoneCode: "679",
      currencyCode: "FJD",
      currencyName: "Fijian dollar", 
      isPicked: false),
  Country(
      name: "Falkland Islands (Malvinas)",
      isoCode: "FK",
      iso3Code: "FLK",
      phoneCode: "500",
      currencyCode: "FKP",
      currencyName: "Falkland Islands pound", 
      isPicked: false),
  Country(
      name: "Micronesia, Federated States of",
      isoCode: "FM",
      iso3Code: "FSM",
      phoneCode: "691",
      currencyCode: "None",
      currencyName: "[D]", 
      isPicked: false),
  Country(
      name: "Faroe Islands",
      isoCode: "FO",
      iso3Code: "FRO",
      phoneCode: "298",
      currencyCode: "DKK",
      currencyName: "Danish krone", 
      isPicked: false),
  Country(
      name: "France",
      isoCode: "FR",
      iso3Code: "FRA",
      phoneCode: "33",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Gabon",
      isoCode: "GA",
      iso3Code: "GAB",
      phoneCode: "241",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "United Kingdom",
      isoCode: "GB",
      iso3Code: "GBR",
      phoneCode: "44",
      currencyCode: "GBP",
      currencyName: "British pound", 
      isPicked: false),
  Country(
      name: "Grenada",
      isoCode: "GD",
      iso3Code: "GRD",
      phoneCode: "1-473",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Georgia",
      isoCode: "GE",
      iso3Code: "GEO",
      phoneCode: "995",
      currencyCode: "GEL",
      currencyName: "Georgian Lari", 
      isPicked: false),
  Country(
      name: "French Guiana",
      isoCode: "GF",
      iso3Code: "GUF",
      phoneCode: "594",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Guernsey",
      isoCode: "GG",
      iso3Code: "GGY",
      phoneCode: "44-1481",
      currencyCode: "GBP",
      currencyName: "British pound", 
      isPicked: false),
  Country(
      name: "Ghana",
      isoCode: "GH",
      iso3Code: "GHA",
      phoneCode: "233",
      currencyCode: "GHS",
      currencyName: "Ghanaian cedi", 
      isPicked: false),
  Country(
      name: "Gibraltar",
      isoCode: "GI",
      iso3Code: "GIB",
      phoneCode: "350",
      currencyCode: "GIP",
      currencyName: "Gibraltar pound", 
      isPicked: false),
  Country(
      name: "Greenland",
      isoCode: "GL",
      iso3Code: "GRL",
      phoneCode: "299",
      currencyCode: "DKK",
      currencyName: "Danish krone", 
      isPicked: false),
  Country(
      name: "Gambia",
      isoCode: "GM",
      iso3Code: "GMB",
      phoneCode: "220",
      currencyCode: "GMD",
      currencyName: "Gambian dalasi", 
      isPicked: false),
  Country(
      name: "Guinea",
      isoCode: "GN",
      iso3Code: "GIN",
      phoneCode: "224",
      currencyCode: "GNF",
      currencyName: "Guinean franc", 
      isPicked: false),
  Country(
      name: "Guadeloupe",
      isoCode: "GP",
      iso3Code: "GLP",
      phoneCode: "590",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Equatorial Guinea",
      isoCode: "GQ",
      iso3Code: "GNQ",
      phoneCode: "240",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "Greece",
      isoCode: "GR",
      iso3Code: "GRC",
      phoneCode: "30",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "South Georgia and the South Sandwich Islands",
      isoCode: "GS",
      iso3Code: "SGS",
      phoneCode: "500",
      currencyCode: "GBP",
      currencyName: "British pound", 
      isPicked: false),
  Country(
      name: "Guatemala",
      isoCode: "GT",
      iso3Code: "GTM",
      phoneCode: "502",
      currencyCode: "GTQ",
      currencyName: "Guatemalan quetzal", 
      isPicked: false),
  Country(
      name: "Guam",
      isoCode: "GU",
      iso3Code: "GUM",
      phoneCode: "1-671",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Guinea-Bissau",
      isoCode: "GW",
      iso3Code: "GNB",
      phoneCode: "245",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Guyana",
      isoCode: "GY",
      iso3Code: "GUY",
      phoneCode: "592",
      currencyCode: "GYD",
      currencyName: "Guyanese dollar", 
      isPicked: false),
  Country(
      name: "Hong Kong",
      isoCode: "HK",
      iso3Code: "HKG",
      phoneCode: "852",
      currencyCode: "HKD",
      currencyName: "Hong Kong dollar", 
      isPicked: false),
  Country(
      name: "Heard Island and McDonald Islands",
      isoCode: "HM",
      iso3Code: "HMD",
      phoneCode: "672",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Honduras",
      isoCode: "HN",
      iso3Code: "HND",
      phoneCode: "504",
      currencyCode: "HNL",
      currencyName: "Honduran lempira", 
      isPicked: false),
  Country(
      name: "Croatia",
      isoCode: "HR",
      iso3Code: "HRV",
      phoneCode: "385",
      currencyCode: "HRK",
      currencyName: "Croatian kuna", 
      isPicked: false),
  Country(
      name: "Haiti",
      isoCode: "HT",
      iso3Code: "HTI",
      phoneCode: "509",
      currencyCode: "HTG",
      currencyName: "Haitian gourde", 
      isPicked: false),
  Country(
      name: "Hungary",
      isoCode: "HU",
      iso3Code: "HUN",
      phoneCode: "36",
      currencyCode: "HUF",
      currencyName: "Hungarian forint", 
      isPicked: false),
  Country(
      name: "Indonesia",
      isoCode: "ID",
      iso3Code: "IDN",
      phoneCode: "62",
      currencyCode: "IDR",
      currencyName: "Indonesian rupiah", 
      isPicked: false),
  Country(
      name: "Ireland",
      isoCode: "IE",
      iso3Code: "IRL",
      phoneCode: "353",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Israel",
      isoCode: "IL",
      iso3Code: "ISR",
      phoneCode: "972",
      currencyCode: "ILS",
      currencyName: "Israeli new shekel", 
      isPicked: false),
  Country(
      name: "Isle of Man",
      isoCode: "IM",
      iso3Code: "IMN",
      phoneCode: "44-1624",
      currencyCode: "GBP",
      currencyName: "British pound", 
      isPicked: false),
  Country(
      name: "India",
      isoCode: "IN",
      iso3Code: "IND",
      phoneCode: "91",
      currencyCode: "INR",
      currencyName: "Indian rupee", 
      isPicked: false),
  Country(
      name: "British Indian Ocean Territory",
      isoCode: "IO",
      iso3Code: "IOT",
      phoneCode: "246",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Iraq",
      isoCode: "IQ",
      iso3Code: "IRQ",
      phoneCode: "964",
      currencyCode: "IQD",
      currencyName: "Iraqi dinar", 
      isPicked: false),
  Country(
      name: "Iran, Islamic Republic of",
      isoCode: "IR",
      iso3Code: "IRN",
      phoneCode: "98",
      currencyCode: "IRR",
      currencyName: "Iranian rial", 
      isPicked: false),
  Country(
      name: "Iceland",
      isoCode: "IS",
      iso3Code: "ISL",
      phoneCode: "354",
      currencyCode: "ISK",
      currencyName: "Icelandic króna", 
      isPicked: false),
  Country(
      name: "Italy",
      isoCode: "IT",
      iso3Code: "ITA",
      phoneCode: "39",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Jersey",
      isoCode: "JE",
      iso3Code: "JEY",
      phoneCode: "44-1534",
      currencyCode: "GBP",
      currencyName: "British pound", 
      isPicked: false),
  Country(
      name: "Jamaica",
      isoCode: "JM",
      iso3Code: "JAM",
      phoneCode: "1-876",
      currencyCode: "JMD",
      currencyName: "Jamaican dollar", 
      isPicked: false),
  Country(
      name: "Jordan",
      isoCode: "JO",
      iso3Code: "JOR",
      phoneCode: "962",
      currencyCode: "JOD",
      currencyName: "Jordanian dinar", 
      isPicked: false),
  Country(
      name: "Japan",
      isoCode: "JP",
      iso3Code: "JPN",
      phoneCode: "81",
      currencyCode: "JPY",
      currencyName: "Japanese yen", 
      isPicked: false),
  Country(
      name: "Kenya",
      isoCode: "KE",
      iso3Code: "KEN",
      phoneCode: "254",
      currencyCode: "KES",
      currencyName: "Kenyan shilling", 
      isPicked: false),
  Country(
      name: "Kyrgyzstan",
      isoCode: "KG",
      iso3Code: "KGZ",
      phoneCode: "996",
      currencyCode: "KGS",
      currencyName: "Kyrgyzstani som", 
      isPicked: false),
  Country(
      name: "Cambodia",
      isoCode: "KH",
      iso3Code: "KHM",
      phoneCode: "855",
      currencyCode: "KHR",
      currencyName: "Cambodian riel", 
      isPicked: false),
  Country(
      name: "Kiribati",
      isoCode: "KI",
      iso3Code: "KIR",
      phoneCode: "686",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Comoros",
      isoCode: "KM",
      iso3Code: "COM",
      phoneCode: "269",
      currencyCode: "KMF",
      currencyName: "Comorian franc", 
      isPicked: false),
  Country(
      name: "Saint Kitts and Nevis",
      isoCode: "KN",
      iso3Code: "KNA",
      phoneCode: "1-869",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Korea, Democratic People's Republic of",
      isoCode: "KP",
      iso3Code: "PRK",
      phoneCode: "850",
      currencyCode: "KPW",
      currencyName: "North Korean won", 
      isPicked: false),
  Country(
      name: "Korea, Republic of",
      isoCode: "KR",
      iso3Code: "KOR",
      phoneCode: "82",
      currencyCode: "KRW",
      currencyName: "South Korean won", 
      isPicked: false),
  Country(
      name: "Kuwait",
      isoCode: "KW",
      iso3Code: "KWT",
      phoneCode: "965",
      currencyCode: "KWD",
      currencyName: "Kuwaiti dinar", 
      isPicked: false),
  Country(
      name: "Cayman Islands",
      isoCode: "KY",
      iso3Code: "CYM",
      phoneCode: "1-345",
      currencyCode: "KYD",
      currencyName: "Cayman Islands dollar", 
      isPicked: false),
  Country(
      name: "Kazakhstan",
      isoCode: "KZ",
      iso3Code: "KAZ",
      phoneCode: "7",
      currencyCode: "KZT",
      currencyName: "Kazakhstani tenge", 
      isPicked: false),
  Country(
      name: "Lao People's Democratic Republic",
      isoCode: "LA",
      iso3Code: "LAO",
      phoneCode: "",
      currencyCode: "LAK",
      currencyName: "Lao kip", 
      isPicked: false),
  Country(
      name: "Lebanon",
      isoCode: "LB",
      iso3Code: "LBN",
      phoneCode: "961",
      currencyCode: "LBP",
      currencyName: "Lebanese pound", 
      isPicked: false),
  Country(
      name: "Saint Lucia",
      isoCode: "LC",
      iso3Code: "LCA",
      phoneCode: "1-758",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Liechtenstein",
      isoCode: "LI",
      iso3Code: "LIE",
      phoneCode: "423",
      currencyCode: "CHF",
      currencyName: "Swiss franc", 
      isPicked: false),
  Country(
      name: "Sri Lanka",
      isoCode: "LK",
      iso3Code: "LKA",
      phoneCode: "94",
      currencyCode: "LKR",
      currencyName: "Sri Lankan rupee", 
      isPicked: false),
  Country(
      name: "Liberia",
      isoCode: "LR",
      iso3Code: "LBR",
      phoneCode: "231",
      currencyCode: "LRD",
      currencyName: "Liberian dollar", 
      isPicked: false),
  Country(
      name: "Lesotho",
      isoCode: "LS",
      iso3Code: "LSO",
      phoneCode: "266",
      currencyCode: "LSL",
      currencyName: "Lesotho loti", 
      isPicked: false),
  Country(
      name: "Lithuania",
      isoCode: "LT",
      iso3Code: "LTU",
      phoneCode: "370",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Luxembourg",
      isoCode: "LU",
      iso3Code: "LUX",
      phoneCode: "352",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Latvia",
      isoCode: "LV",
      iso3Code: "LVA",
      phoneCode: "371",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Libya",
      isoCode: "LY",
      iso3Code: "LBY",
      phoneCode: "218",
      currencyCode: "LYD",
      currencyName: "Libyan dinar", 
      isPicked: false),
  Country(
      name: "Morocco",
      isoCode: "MA",
      iso3Code: "MAR",
      phoneCode: "212",
      currencyCode: "MAD",
      currencyName: "Moroccan dirham", 
      isPicked: false),
  Country(
      name: "Monaco",
      isoCode: "MC",
      iso3Code: "MCO",
      phoneCode: "377",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Moldova, Republic of",
      isoCode: "MD",
      iso3Code: "MDA",
      phoneCode: "373",
      currencyCode: "MDL",
      currencyName: "Moldovan leu", 
      isPicked: false),
  Country(
      name: "Montenegro",
      isoCode: "ME",
      iso3Code: "MNE",
      phoneCode: "382",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Saint Martin",
      isoCode: "MF",
      iso3Code: "MAF",
      phoneCode: "590",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Madagascar",
      isoCode: "MG",
      iso3Code: "MDG",
      phoneCode: "261",
      currencyCode: "MGA",
      currencyName: "Malagasy ariary", 
      isPicked: false),
  Country(
      name: "Marshall Islands",
      isoCode: "MH",
      iso3Code: "MHL",
      phoneCode: "692",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Macedonia, the former Yugoslav Republic of",
      isoCode: "MK",
      iso3Code: "MKD",
      phoneCode: "389",
      currencyCode: "MKD",
      currencyName: "Macedonian denar", 
      isPicked: false),
  Country(
      name: "Mali",
      isoCode: "ML",
      iso3Code: "MLI",
      phoneCode: "223",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Myanmar",
      isoCode: "MM",
      iso3Code: "MMR",
      phoneCode: "95",
      currencyCode: "MMK",
      currencyName: "Burmese kyat", 
      isPicked: false),
  Country(
      name: "Mongolia",
      isoCode: "MN",
      iso3Code: "MNG",
      phoneCode: "976",
      currencyCode: "MNT",
      currencyName: "Mongolian tögrög", 
      isPicked: false),
  Country(
      name: "Macao",
      isoCode: "MO",
      iso3Code: "MAC",
      phoneCode: "853",
      currencyCode: "MOP",
      currencyName: "Macanese pataca", 
      isPicked: false),
  Country(
      name: "Northern Mariana Islands",
      isoCode: "MP",
      iso3Code: "MNP",
      phoneCode: "1-670",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Martinique",
      isoCode: "MQ",
      iso3Code: "MTQ",
      phoneCode: "596",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Mauritania",
      isoCode: "MR",
      iso3Code: "MRT",
      phoneCode: "222",
      currencyCode: "MRO",
      currencyName: "Mauritanian ouguiya", 
      isPicked: false),
  Country(
      name: "Montserrat",
      isoCode: "MS",
      iso3Code: "MSR",
      phoneCode: "1-664",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Malta",
      isoCode: "MT",
      iso3Code: "MLT",
      phoneCode: "356",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Mauritius",
      isoCode: "MU",
      iso3Code: "MUS",
      phoneCode: "230",
      currencyCode: "MUR",
      currencyName: "Mauritian rupee", 
      isPicked: false),
  Country(
      name: "Maldives",
      isoCode: "MV",
      iso3Code: "MDV",
      phoneCode: "960",
      currencyCode: "MVR",
      currencyName: "Maldivian rufiyaa", 
      isPicked: false),
  Country(
      name: "Malawi",
      isoCode: "MW",
      iso3Code: "MWI",
      phoneCode: "265",
      currencyCode: "MWK",
      currencyName: "Malawian kwacha", 
      isPicked: false),
  Country(
      name: "Mexico",
      isoCode: "MX",
      iso3Code: "MEX",
      phoneCode: "52",
      currencyCode: "MXN",
      currencyName: "Mexican peso", 
      isPicked: false),
  Country(
      name: "Malaysia",
      isoCode: "MY",
      iso3Code: "MYS",
      phoneCode: "60",
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit", 
      isPicked: false),
  Country(
      name: "Mozambique",
      isoCode: "MZ",
      iso3Code: "MOZ",
      phoneCode: "258",
      currencyCode: "MZN",
      currencyName: "Mozambican metical", 
      isPicked: false),
  Country(
      name: "Namibia",
      isoCode: "NA",
      iso3Code: "NAM",
      phoneCode: "264",
      currencyCode: "NAD",
      currencyName: "Namibian dollar", 
      isPicked: false),
  Country(
      name: "New Caledonia",
      isoCode: "NC",
      iso3Code: "NCL",
      phoneCode: "687",
      currencyCode: "XPF",
      currencyName: "CFP franc", 
      isPicked: false),
  Country(
      name: "Niger",
      isoCode: "NE",
      iso3Code: "NER",
      phoneCode: "227",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Norfolk Island",
      isoCode: "NF",
      iso3Code: "NFK",
      phoneCode: "672",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Nigeria",
      isoCode: "NG",
      iso3Code: "NGA",
      phoneCode: "234",
      currencyCode: "NGN",
      currencyName: "Nigerian naira", 
      isPicked: false),
  Country(
      name: "Nicaragua",
      isoCode: "NI",
      iso3Code: "NIC",
      phoneCode: "505",
      currencyCode: "NIO",
      currencyName: "Nicaraguan córdoba", 
      isPicked: false),
  Country(
      name: "Netherlands",
      isoCode: "NL",
      iso3Code: "NLD",
      phoneCode: "31",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Norway",
      isoCode: "NO",
      iso3Code: "NOR",
      phoneCode: "47",
      currencyCode: "NOK",
      currencyName: "Norwegian krone", 
      isPicked: false),
  Country(
      name: "Nepal",
      isoCode: "NP",
      iso3Code: "NPL",
      phoneCode: "977",
      currencyCode: "NPR",
      currencyName: "Nepalese rupee", 
      isPicked: false),
  Country(
      name: "Nauru",
      isoCode: "NR",
      iso3Code: "NRU",
      phoneCode: "674",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Niue",
      isoCode: "NU",
      iso3Code: "NIU",
      phoneCode: "683",
      currencyCode: "NZD",
      currencyName: "New Zealand dollar", 
      isPicked: false),
  Country(
      name: "New Zealand",
      isoCode: "NZ",
      iso3Code: "NZL",
      phoneCode: "64",
      currencyCode: "NZD",
      currencyName: "New Zealand dollar", 
      isPicked: false),
  Country(
      name: "Oman",
      isoCode: "OM",
      iso3Code: "OMN",
      phoneCode: "968",
      currencyCode: "OMR",
      currencyName: "Omani rial", 
      isPicked: false),
  Country(
      name: "Panama",
      isoCode: "PA",
      iso3Code: "PAN",
      phoneCode: "507",
      currencyCode: "PAB",
      currencyName: "Panamanian balboa", 
      isPicked: false),
  Country(
      name: "Peru",
      isoCode: "PE",
      iso3Code: "PER",
      phoneCode: "51",
      currencyCode: "PEN",
      currencyName: "Peruvian sol", 
      isPicked: false),
  Country(
      name: "French Polynesia",
      isoCode: "PF",
      iso3Code: "PYF",
      phoneCode: "689",
      currencyCode: "XPF",
      currencyName: "CFP franc", 
      isPicked: false),
  Country(
      name: "Papua New Guinea",
      isoCode: "PG",
      iso3Code: "PNG",
      phoneCode: "675",
      currencyCode: "PGK",
      currencyName: "Papua New Guinean kina", 
      isPicked: false),
  Country(
      name: "Philippines",
      isoCode: "PH",
      iso3Code: "PHL",
      phoneCode: "63",
      currencyCode: "PHP",
      currencyName: "Philippine peso", 
      isPicked: false),
  Country(
      name: "Pakistan",
      isoCode: "PK",
      iso3Code: "PAK",
      phoneCode: "92",
      currencyCode: "PKR",
      currencyName: "Pakistani rupee", 
      isPicked: false),
  Country(
      name: "Poland",
      isoCode: "PL",
      iso3Code: "POL",
      phoneCode: "48",
      currencyCode: "PLN",
      currencyName: "Polish złoty", 
      isPicked: false),
  Country(
      name: "Saint Pierre and Miquelon",
      isoCode: "PM",
      iso3Code: "SPM",
      phoneCode: "508",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Pitcairn",
      isoCode: "PN",
      iso3Code: "PCN",
      phoneCode: "64",
      currencyCode: "NZD",
      currencyName: "New Zealand dollar", 
      isPicked: false),
  Country(
      name: "Puerto Rico",
      isoCode: "PR",
      iso3Code: "PRI",
      phoneCode: "1-787",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Palestine",
      isoCode: "PS",
      iso3Code: "PSE",
      phoneCode: "970",
      currencyCode: "ILS",
      currencyName: "Israeli new sheqel", 
      isPicked: false),
  Country(
      name: "Portugal",
      isoCode: "PT",
      iso3Code: "PRT",
      phoneCode: "351",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Palau",
      isoCode: "PW",
      iso3Code: "PLW",
      phoneCode: "680",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Paraguay",
      isoCode: "PY",
      iso3Code: "PRY",
      phoneCode: "595",
      currencyCode: "PYG",
      currencyName: "Paraguayan guaraní", 
      isPicked: false),
  Country(
      name: "Qatar",
      isoCode: "QA",
      iso3Code: "QAT",
      phoneCode: "974",
      currencyCode: "QAR",
      currencyName: "Qatari riyal", 
      isPicked: false),
  Country(
      name: "Réunion",
      isoCode: "RE",
      iso3Code: "REU",
      phoneCode: "262",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Romania",
      isoCode: "RO",
      iso3Code: "ROU",
      phoneCode: "40",
      currencyCode: "RON",
      currencyName: "Romanian leu", 
      isPicked: false),
  Country(
      name: "Serbia",
      isoCode: "RS",
      iso3Code: "SRB",
      phoneCode: "381",
      currencyCode: "RSD",
      currencyName: "Serbian dinar", 
      isPicked: false),
  Country(
      name: "Russian Federation",
      isoCode: "RU",
      iso3Code: "RUS",
      phoneCode: "7",
      currencyCode: "RUB",
      currencyName: "Russian ruble", 
      isPicked: false),
  Country(
      name: "Rwanda",
      isoCode: "RW",
      iso3Code: "RWA",
      phoneCode: "250",
      currencyCode: "RWF",
      currencyName: "Rwandan franc", 
      isPicked: false),
  Country(
      name: "Saudi Arabia",
      isoCode: "SA",
      iso3Code: "SAU",
      phoneCode: "966",
      currencyCode: "SAR",
      currencyName: "Saudi riyal", 
      isPicked: false),
  Country(
      name: "Solomon Islands",
      isoCode: "SB",
      iso3Code: "SLB",
      phoneCode: "677",
      currencyCode: "SBD",
      currencyName: "Solomon Islands dollar", 
      isPicked: false),
  Country(
      name: "Seychelles",
      isoCode: "SC",
      iso3Code: "SYC",
      phoneCode: "248",
      currencyCode: "SCR",
      currencyName: "Seychellois rupee", 
      isPicked: false),
  Country(
      name: "Sudan",
      isoCode: "SD",
      iso3Code: "SDN",
      phoneCode: "249",
      currencyCode: "SDG",
      currencyName: "Sudanese pound", 
      isPicked: false),
  Country(
      name: "Sweden",
      isoCode: "SE",
      iso3Code: "SWE",
      phoneCode: "46",
      currencyCode: "SEK",
      currencyName: "Swedish krona", 
      isPicked: false),
  Country(
      name: "Singapore",
      isoCode: "SG",
      iso3Code: "SGP",
      phoneCode: "65",
      currencyCode: "SGD",
      currencyName: "Singapore dollar", 
      isPicked: false),
  Country(
      name: "Saint Helena, Ascension and Tristan da Cunha",
      isoCode: "SH",
      iso3Code: "SHN",
      phoneCode: "290",
      currencyCode: "SHP",
      currencyName: "Saint Helena pound", 
      isPicked: false),
  Country(
      name: "Slovenia",
      isoCode: "SI",
      iso3Code: "SVN",
      phoneCode: "386",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Svalbard and Jan Mayen Islands",
      isoCode: "SJ",
      iso3Code: "SJM",
      phoneCode: "47",
      currencyCode: "NOK",
      currencyName: "Norwegian krone", 
      isPicked: false),
  Country(
      name: "Slovakia",
      isoCode: "SK",
      iso3Code: "SVK",
      phoneCode: "421",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Sierra Leone",
      isoCode: "SL",
      iso3Code: "SLE",
      phoneCode: "232",
      currencyCode: "SLL",
      currencyName: "Sierra Leonean leone", 
      isPicked: false),
  Country(
      name: "San Marino",
      isoCode: "SM",
      iso3Code: "SMR",
      phoneCode: "378",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Senegal",
      isoCode: "SN",
      iso3Code: "SEN",
      phoneCode: "221",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Somalia",
      isoCode: "SO",
      iso3Code: "SOM",
      phoneCode: "252",
      currencyCode: "SOS",
      currencyName: "Somali shilling", 
      isPicked: false),
  Country(
      name: "Suriname",
      isoCode: "SR",
      iso3Code: "SUR",
      phoneCode: "597",
      currencyCode: "SRD",
      currencyName: "Surinamese dollar", 
      isPicked: false),
  Country(
      name: "South Sudan",
      isoCode: "SS",
      iso3Code: "SSD",
      phoneCode: "211",
      currencyCode: "SSP",
      currencyName: "South Sudanese pound", 
      isPicked: false),
  Country(
      name: "Sao Tome and Principe",
      isoCode: "ST",
      iso3Code: "STP",
      phoneCode: "239",
      currencyCode: "STD",
      currencyName: "São Tomé and Príncipe dobra", 
      isPicked: false),
  Country(
      name: "El Salvador",
      isoCode: "SV",
      iso3Code: "SLV",
      phoneCode: "503",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Sint Maarten (Dutch part)",
      isoCode: "SX",
      iso3Code: "SXM",
      phoneCode: "1-721",
      currencyCode: "ANG",
      currencyName: "Netherlands Antillean guilder", 
      isPicked: false),
  Country(
      name: "Syrian Arab Republic",
      isoCode: "SY",
      iso3Code: "SYR",
      phoneCode: "963",
      currencyCode: "SYP",
      currencyName: "Syrian pound", 
      isPicked: false),
  Country(
      name: "Swaziland",
      isoCode: "SZ",
      iso3Code: "SWZ",
      phoneCode: "268",
      currencyCode: "SZL",
      currencyName: "Swazi lilangeni", 
      isPicked: false),
  Country(
      name: "Turks and Caicos Islands",
      isoCode: "TC",
      iso3Code: "TCA",
      phoneCode: "1-649",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Chad",
      isoCode: "TD",
      iso3Code: "TCD",
      phoneCode: "235",
      currencyCode: "XAF",
      currencyName: "Central African CFA franc", 
      isPicked: false),
  Country(
      name: "French Southern Territories",
      isoCode: "TF",
      iso3Code: "ATF",
      phoneCode: "262",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Togo",
      isoCode: "TG",
      iso3Code: "TGO",
      phoneCode: "228",
      currencyCode: "XOF",
      currencyName: "West African CFA franc", 
      isPicked: false),
  Country(
      name: "Thailand",
      isoCode: "TH",
      iso3Code: "THA",
      phoneCode: "66",
      currencyCode: "THB",
      currencyName: "Thai baht", 
      isPicked: false),
  Country(
      name: "Tajikistan",
      isoCode: "TJ",
      iso3Code: "TJK",
      phoneCode: "992",
      currencyCode: "TJS",
      currencyName: "Tajikistani somoni", 
      isPicked: false),
  Country(
      name: "Tokelau",
      isoCode: "TK",
      iso3Code: "TKL",
      phoneCode: "690",
      currencyCode: "NZD",
      currencyName: "New Zealand dollar", 
      isPicked: false),
  Country(
      name: "Timor-Leste",
      isoCode: "TL",
      iso3Code: "TLS",
      phoneCode: "670",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Turkmenistan",
      isoCode: "TM",
      iso3Code: "TKM",
      phoneCode: "993",
      currencyCode: "TMT",
      currencyName: "Turkmenistan manat", 
      isPicked: false),
  Country(
      name: "Tunisia",
      isoCode: "TN",
      iso3Code: "TUN",
      phoneCode: "216",
      currencyCode: "TND",
      currencyName: "Tunisian dinar", 
      isPicked: false),
  Country(
      name: "Tonga",
      isoCode: "TO",
      iso3Code: "TON",
      phoneCode: "676",
      currencyCode: "TOP",
      currencyName: "Tongan paʻanga", 
      isPicked: false),
  Country(
      name: "Turkey",
      isoCode: "TR",
      iso3Code: "TUR",
      phoneCode: "90",
      currencyCode: "TRY",
      currencyName: "Turkish lira", 
      isPicked: false),
  Country(
      name: "Trinidad and Tobago",
      isoCode: "TT",
      iso3Code: "TTO",
      phoneCode: "1-868",
      currencyCode: "TTD",
      currencyName: "Trinidad and Tobago dollar", 
      isPicked: false),
  Country(
      name: "Tuvalu",
      isoCode: "TV",
      iso3Code: "TUV",
      phoneCode: "688",
      currencyCode: "AUD",
      currencyName: "Australian dollar", 
      isPicked: false),
  Country(
      name: "Taiwan",
      isoCode: "TW",
      iso3Code: "TWN",
      phoneCode: "886",
      currencyCode: "TWD",
      currencyName: "New Taiwan dollar", 
      isPicked: false),
  Country(
      name: "Tanzania, United Republic of",
      isoCode: "TZ",
      iso3Code: "TZA",
      phoneCode: "255",
      currencyCode: "TZS",
      currencyName: "Tanzanian shilling", 
      isPicked: false),
  Country(
      name: "Ukraine",
      isoCode: "UA",
      iso3Code: "UKR",
      phoneCode: "380",
      currencyCode: "UAH",
      currencyName: "Ukrainian hryvnia", 
      isPicked: false),
  Country(
      name: "Uganda",
      isoCode: "UG",
      iso3Code: "UGA",
      phoneCode: "256",
      currencyCode: "UGX",
      currencyName: "Ugandan shilling", 
      isPicked: false),
  Country(
      name: "United States",
      isoCode: "US",
      iso3Code: "USA",
      phoneCode: "1",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Uruguay",
      isoCode: "UY",
      iso3Code: "URY",
      phoneCode: "598",
      currencyCode: "UYU",
      currencyName: "Uruguayan peso", 
      isPicked: false),
  Country(
      name: "Uzbekistan",
      isoCode: "UZ",
      iso3Code: "UZB",
      phoneCode: "998",
      currencyCode: "UZS",
      currencyName: "Uzbekistani so'm", 
      isPicked: false),
  Country(
      name: "Holy See (Vatican City State)",
      isoCode: "VA",
      iso3Code: "VAT",
      phoneCode: "379",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Saint Vincent and the Grenadines",
      isoCode: "VC",
      iso3Code: "VCT",
      phoneCode: "1-784",
      currencyCode: "XCD",
      currencyName: "East Caribbean dollar", 
      isPicked: false),
  Country(
      name: "Venezuela, Bolivarian Republic of",
      isoCode: "VE",
      iso3Code: "VEN",
      phoneCode: "58",
      currencyCode: "VEF",
      currencyName: "Venezuelan bolívar", 
      isPicked: false),
  Country(
      name: "Virgin Islands, British",
      isoCode: "VG",
      iso3Code: "VGB",
      phoneCode: "1-284",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Virgin Islands, U.S.",
      isoCode: "VI",
      iso3Code: "VIR",
      phoneCode: "1-340",
      currencyCode: "USD",
      currencyName: "United States dollar", 
      isPicked: false),
  Country(
      name: "Vietnam",
      isoCode: "VN",
      iso3Code: "VNM",
      phoneCode: "84",
      currencyCode: "VND",
      currencyName: "Vietnamese đồng", 
      isPicked: false),
  Country(
      name: "Vanuatu",
      isoCode: "VU",
      iso3Code: "VUT",
      phoneCode: "678",
      currencyCode: "VUV",
      currencyName: "Vanuatu vatu", 
      isPicked: false),
  Country(
      name: "Wallis and Futuna Islands",
      isoCode: "WF",
      iso3Code: "WLF",
      phoneCode: "681",
      currencyCode: "XPF",
      currencyName: "CFP franc", 
      isPicked: false),
  Country(
      name: "Kosovo",
      isoCode: "XK",
      iso3Code: "KOS",
      phoneCode: "383",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "Samoa",
      isoCode: "WS",
      iso3Code: "WSM",
      phoneCode: "685",
      currencyCode: "WST",
      currencyName: "Samoan tālā", 
      isPicked: false),
  Country(
      name: "Yemen",
      isoCode: "YE",
      iso3Code: "YEM",
      phoneCode: "967",
      currencyCode: "YER",
      currencyName: "Yemeni rial", 
      isPicked: false),
  Country(
      name: "Mayotte",
      isoCode: "YT",
      iso3Code: "MYT",
      phoneCode: "262",
      currencyCode: "EUR",
      currencyName: "Euro", 
      isPicked: false),
  Country(
      name: "South Africa",
      isoCode: "ZA",
      iso3Code: "ZAF",
      phoneCode: "27",
      currencyCode: "ZAR",
      currencyName: "South African rand", 
      isPicked: false),
  Country(
      name: "Zambia",
      isoCode: "ZM",
      iso3Code: "ZMB",
      phoneCode: "260",
      currencyCode: "ZMW",
      currencyName: "Zambian kwacha", 
      isPicked: false),
  Country(
      name: "Zimbabwe",
      isoCode: "ZW",
      iso3Code: "ZWE",
      phoneCode: "263",
      currencyCode: "BWP",
      currencyName: "Botswana pula",
      isPicked: false)
];
