Map<String, String> cryptoNetworksMap = {
   "BTC": "Bitcoin",
  "ETH": "Ethereum",
  "USDT": "Tether",
  "BNB": "Binance Coin",
  "XRP": "XRP",
  "ADA": "Cardano",
  "DOGE": "Dogecoin",
  "SOL": "Solana",
  "MATIC": "Polygon",
  "DOT": "Polkadot",
  "LTC": "Litecoin",
  "SHIB": "Shiba Inu",
  "AVAX": "Avalanche",
  "TRX": "TRON",
  "DAI": "Dai",
  "LINK": "Chainlink",
  "ATOM": "Cosmos",
  "ETC": "Ethereum Classic",
  "XMR": "Monero",
  "BCH": "Bitcoin Cash",
  "XLM": "Stellar",
  "ALGO": "Algorand",
  "APT": "Aptos",
  "FIL": "Filecoin",
  "QNT": "Quant",
  "VET": "VeChain",
  "ICP": "Internet Computer",
  "NEAR": "NEAR Protocol",
  "HNT": "Helium",
  "FTM": "Fantom",
  "HBAR": "Hedera",
  "SAND": "The Sandbox",
  "MANA": "Decentraland",
  "AAVE": "Aave",
  "EOS": "EOS",
  "GRT": "The Graph",
  "RUNE": "THORChain",
  "ZIL": "Zilliqa",
  "CRO": "Cronos",
  "XDC": "XDC Network",
  "KSM": "Kusama",
  "CAKE": "PancakeSwap",
  "ENJ": "Enjin Coin",
  "BAT": "Basic Attention Token",
  "LRC": "Loopring",
  "KAVA": "Kava",
  "CELO": "Celo",
  "1INCH": "1inch",
  "GALA": "Gala",
  "ROSE": "Oasis Network",
  "OMG": "OMG Network",
  "IOTA": "IOTA",
  "AR": "Arweave",
  "MINA": "Mina",
  "ZRX": "0x",
  "REN": "Ren",
  "SNX": "Synthetix",
  "COMP": "Compound",
  "UMA": "UMA",
  "BAL": "Balancer",
  "LPT": "Livepeer",
  "SUSHI": "SushiSwap",
  "YFI": "yearn.finance",
  "ANKR": "Ankr",
  "RLC": "iExec RLC",
  "QTUM": "Qtum",
  "CHZ": "Chiliz",
  "STORJ": "Storj",
  "DGB": "DigiByte",
  "SKL": "SKALE",
  "REQ": "Request",
  "DENT": "Dent",
  "POLY": "Polymath",
  "BNT": "Bancor",
  "MLN": "Enzyme",
  "COTI": "COTI",
  "FUN": "FunFair",
  "PAXG": "Pax Gold",
  "TRB": "Tellor",
  "OGN": "Origin Protocol",
  "TOMO": "TomoChain",
  "REP": "Augur",
  "XNO": "Nano",
  "KEEP": "Keep Network",
  "PHA": "Phala Network",
  "ORN": "Orion Protocol",
  "RAY": "Raydium",
  "BAKE": "BakerySwap",
  "AKRO": "Akropolis",
  "PERP": "Perpetual Protocol",
  "MIR": "Mirror Protocol",
  "MFT": "Mainframe",
  "WNXM": "Wrapped NXM",
  "POLS": "Polkastarter",
  "WNXM": "Wrapped NXM",
  "BOND": "BarnBridge",
  "DEGO": "Dego Finance",
  "OCEAN": "Ocean Protocol",
  "BLZ": "Bluzelle",
  "ALPHA": "Alpha Finance Lab"
};
